%Import_data script
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: D:\Compiled Data\Data Sets for Thesis\P21 STM data.csv
%
% Auto-generated by MATLAB on 28-Feb-2021 19:51:12

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 21, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["RefNumber", "NerveTerminalPerimeterum", "NerveTerminalAreaum2", "TotalLengthOfBranchesum", "AverageLengthOfBranchesum", "Complexity", "AChRPerimeterum", "AChRAreaum2", "EndplateDiameterum", "EndplatePerimeterum", "EndplateAreaum2", "Compactness", "UnoccupiedAChRAreaum2", "AreaOfSynapticContactum2", "Overlap", "ManualEndplateAreaum2", "ManualCompactness", "Fragmentation", "Animal", "Genotype", "Gender"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "categorical", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "RefNumber", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["RefNumber", "Animal", "Genotype", "Gender"], "EmptyFieldRule", "auto");

% Import the data
P21STMdata = readtable("D:\Compiled Data\Data Sets for Thesis\P21 STM data.csv", opts);


%% Clear temporary variables
clear opts