%stats_test
%Data analysis test script
%To test how to perform stats in MATLAB before writing function

%First need to import data - see autogenerated MATLAB data import script
NMJ_data = table2array(P21STMdata(:,[2:8,14:18])); %convert table to array for stats
%disp(NMJ_data); can remove % to check if array correct

%basic stats on data - mean, median, standard deviation
mean_col = mean(NMJ_data);
med_col = median(NMJ_data);
std_col = std(NMJ_data);

%stats by genotype only (if gender = false in function input)
for ii = 1:size(NMJ_array,2)
%test generalized linear model with several distributions for each set of
%measurements - poisson, normal, lognormal, gamma
%also need to test beta distribution fit - separate command
fitglm(NMJ_array(:,ii));
%how to add model: Measurement~Genotype
end

%stats by gender and genotype (if gender = true in function input)
for ii = 1:size(NMJ_array,2)
%test generalized linear model with several distributions for each set of
%measurements - poisson, normal, lognormal, gamma
%also need to test beta distribution fit - separate command
fitglm(NMJ_array(:,ii));
%how to add model: Measurement~Genotype*Gender
end