%stats_test
%Data analysis test script
%To test how to perform stats in MATLAB before writing function

%First need to import data - see autogenerated MATLAB data import script
NMJ_data = table2array(P21STMdata(:,[2:8,14:18])); %convert table to array for stats?
%disp(NMJ_data); can remove % to check if array correct

%separate data into WT and HOM by genotype, convert to arrays for stats
HOM_data = P21STMdata(P21STMdata.Genotype == 'HOM',:);
HOM_array = table2array(HOM_data(:,[2:8,14:18]));
WT_data = P21STMdata(P21STMdata.Genotype == 'WT',:);
WT_array = table2array(WT_data(:,[2:8,14:18]));

%basic stats on data - mean, median, standard deviation
mean_WT = mean(WT_array);
mean_HOM = mean(HOM_array);
med_WT = median(WT_array);
med_HOM = median(HOM_array);
std_WT = std(WT_array);
std_HOM = std(HOM_array);

%stats by genotype only (if gender = false in function input)
for ii = 1:size(NMJ_array,2)
%test generalized linear model with several distributions for each set of
%measurements - poisson, normal, lognormal, gamma
%also need to test beta distribution fit - separate command
fitglm(NMJ_array(:,ii));
%how to add model: Measurement~Genotype
end

%stats by gender and genotype (if gender = true in function input)
for ii = 1:size(NMJ_array,2)
%test generalized linear model with several distributions for each set of
%measurements - poisson, normal, lognormal, gamma
%also need to test beta distribution fit - separate command
fitglm(NMJ_array(:,ii));
%how to add model: Measurement~Genotype*Gender
end